sergelogvinov/proxmox-cloud-controller-manager

- .github/workflows/release-pre.yaml
- CHANGELOG.md
- Makefile
- charts/proxmox-cloud-controller-manager/Chart.yaml
- charts/proxmox-cloud-controller-manager/README.md
- docs/deploy/cloud-controller-manager-talos.yml
- docs/deploy/cloud-controller-manager.yml
- docs/release.md
> chore: release v0.0.1

- CHANGELOG.md
- charts/proxmox-cloud-controller-manager/Chart.yaml
- charts/proxmox-cloud-controller-manager/README.md
- docs/deploy/cloud-controller-manager-talos.yml
- docs/deploy/cloud-controller-manager.yml
> chore: release v0.1.0

- CHANGELOG.md
- Dockerfile
- charts/proxmox-cloud-controller-manager/Chart.yaml
- charts/proxmox-cloud-controller-manager/README.md
- docs/deploy/cloud-controller-manager-talos.yml
- docs/deploy/cloud-controller-manager.yml
> chore: release v0.1.1

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/workflows/release-charts.yaml
- Makefile
> feat: helm oci release

- .dockerignore
- .github/dependabot.yml
- .github/workflows/build-edge.yaml
- .github/workflows/build-test.yaml
- .github/workflows/charts.yaml
- .github/workflows/conform.yaml
- .github/workflows/release-charts.yaml
- .github/workflows/release.yaml
- .gitignore
- Makefile
- docs/cosign.md
It helps to check that image was build in github-actions.
> feat: cosign images

- cmd/proxmox-cloud-controller-manager/main.go
- pkg/proxmox/cloud.go
proxmox.Init() func does not load in boot time.
> fix: init provider

- CHANGELOG.md
- Makefile
- charts/proxmox-cloud-controller-manager/Chart.yaml
- charts/proxmox-cloud-controller-manager/README.md
- docs/deploy/cloud-controller-manager-talos.yml
- docs/deploy/cloud-controller-manager.yml
> chore: release v0.4.0

- .gitignore
- charts/proxmox-cloud-controller-manager/Chart.yaml
- charts/proxmox-cloud-controller-manager/README.md
- charts/proxmox-cloud-controller-manager/templates/deployment.yaml
- charts/proxmox-cloud-controller-manager/values.yaml
- docs/deploy/cloud-controller-manager-talos.yml
- docs/deploy/cloud-controller-manager.yml
- docs/loadbalancer.md
It helps to deploy CCM with load blancer as sidecar.
> feat(chart): add hostAliases and initContainers

- .github/workflows/build-edge.yaml
Github action changes base image, we need to install qemu binaries.
> chore(cicd): update multi arch build init

- Makefile
Github action changes base image, we need to install qemu binaries.
> ci: update multi arch build init

- CHANGELOG.md
- charts/proxmox-cloud-controller-manager/Chart.yaml
- charts/proxmox-cloud-controller-manager/README.md
- charts/proxmox-cloud-controller-manager/README.md.gotmpl
- docs/deploy/cloud-controller-manager-daemonset.yml
- docs/deploy/cloud-controller-manager-talos.yml
- docs/deploy/cloud-controller-manager.yml
> chore: release v0.4.1

- .github/workflows/release.yaml
- CHANGELOG.md
- charts/proxmox-cloud-controller-manager/Chart.yaml
- charts/proxmox-cloud-controller-manager/README.md
- docs/deploy/cloud-controller-manager-daemonset.yml
- docs/deploy/cloud-controller-manager-talos.yml
- docs/deploy/cloud-controller-manager.yml
Release v0.4.2
Build multi arch fix 
> chore: release v0.4.2

- CHANGELOG.md
- charts/proxmox-cloud-controller-manager/Chart.yaml
- charts/proxmox-cloud-controller-manager/README.md
- charts/proxmox-cloud-controller-manager/templates/deployment.yaml
- docs/deploy/cloud-controller-manager-daemonset.yml
- docs/deploy/cloud-controller-manager-talos.yml
- docs/deploy/cloud-controller-manager.yml
- docs/release.md
> chore: release v0.5.0

- Dockerfile
- Makefile
- pkg/proxmox/instances.go
The node might be down when we try to retrieve the instance property.
closes #147 
> fix: instance type

- CHANGELOG.md
- charts/proxmox-cloud-controller-manager/Chart.yaml
- charts/proxmox-cloud-controller-manager/README.md
- charts/proxmox-cloud-controller-manager/values.yaml
- docs/deploy/cloud-controller-manager-daemonset.yml
- docs/deploy/cloud-controller-manager-talos.yml
- docs/deploy/cloud-controller-manager.yml
> chore: release v0.5.1

- charts/proxmox-cloud-controller-manager/Chart.yaml
- charts/proxmox-cloud-controller-manager/README.md
- charts/proxmox-cloud-controller-manager/README.md.gotmpl
- docs/deploy/cloud-controller-manager-daemonset.yml
- docs/deploy/cloud-controller-manager-talos.yml
- docs/deploy/cloud-controller-manager.yml
- docs/install.md
Add kubelet requirements to the install process.
> docs: kubelet flags

- docs/install.md
Add troubleshooting recomendation
> docs: troubleshooting

- README.md
- docs/faq.md
- docs/install.md
Add fast answers to common questions
> docs: add faq

- CHANGELOG.md
- charts/proxmox-cloud-controller-manager/Chart.yaml
- charts/proxmox-cloud-controller-manager/README.md
- docs/deploy/cloud-controller-manager-daemonset.yml
- docs/deploy/cloud-controller-manager-talos.yml
- docs/deploy/cloud-controller-manager.yml
> chore: release v0.6.0

- CHANGELOG.md
- charts/proxmox-cloud-controller-manager/Chart.yaml
- charts/proxmox-cloud-controller-manager/README.md
- docs/deploy/cloud-controller-manager-daemonset.yml
- docs/deploy/cloud-controller-manager-talos.yml
- docs/deploy/cloud-controller-manager.yml
> chore: release v0.7.0

- .github/PULL_REQUEST_TEMPLATE.md
- pkg/cluster/client.go
- pkg/proxmox/instances.go
- pkg/proxmox/instances_test.go
We will find the node by name more precisely.
Check the UUID and VM name to determine the VM ID.
> fix: find node by name

- pkg/cluster/client.go
- pkg/proxmox/instances.go
- pkg/proxmox/instances_test.go
Now, we can set a custom instance type using the smbios1[sku] argument
> feat: custom instance type

- charts/proxmox-cloud-controller-manager/Chart.yaml
- charts/proxmox-cloud-controller-manager/ci/values.yaml
- charts/proxmox-cloud-controller-manager/templates/deployment.yaml
- charts/proxmox-cloud-controller-manager/values.yaml
Add extraEnvs option in helm chart.
> feat(helm): extra envs values

- CHANGELOG.md
- charts/proxmox-cloud-controller-manager/Chart.yaml
- charts/proxmox-cloud-controller-manager/README.md
- docs/deploy/cloud-controller-manager-daemonset.yml
- docs/deploy/cloud-controller-manager-talos.yml
- docs/deploy/cloud-controller-manager.yml
> chore: release v0.8.0

- CHANGELOG.md
- charts/proxmox-cloud-controller-manager/Chart.yaml
- charts/proxmox-cloud-controller-manager/README.md
- docs/deploy/cloud-controller-manager-daemonset.yml
- docs/deploy/cloud-controller-manager-talos.yml
- docs/deploy/cloud-controller-manager.yml
> chore: release v0.9.0

- charts/proxmox-cloud-controller-manager/Chart.yaml
- charts/proxmox-cloud-controller-manager/README.md
- charts/proxmox-cloud-controller-manager/README.md.gotmpl
- docs/config.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/proxmoxpool/pool.go
- pkg/proxmoxpool/pool_test.go
This PR allows to read token_id and token_secret from separate file. 
#215 
> Added config option token_id_file & token_secret_file

- go.mod
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- pkg/proxmox/annotation.go
- pkg/proxmox/cloud.go
- pkg/proxmox/cloud_test.go
- pkg/proxmox/errors.go
- pkg/proxmox/instance_addresses.go
- pkg/proxmox/instances.go
- pkg/proxmox/instances_test.go
- pkg/proxmox/utils.go
- pkg/proxmox/utils_test.go
- pkg/proxmoxpool/doc.go
- pkg/proxmoxpool/errors.go
- pkg/proxmoxpool/pool.go
- pkg/proxmoxpool/pool_test.go
Store all important information in instanceInfo struct.
> refactor: instance metadata

- CHANGELOG.md
- charts/proxmox-cloud-controller-manager/Chart.yaml
- charts/proxmox-cloud-controller-manager/README.md
- charts/proxmox-cloud-controller-manager/README.md.gotmpl
- docs/deploy/cloud-controller-manager-daemonset.yml
- docs/deploy/cloud-controller-manager-talos.yml
- docs/deploy/cloud-controller-manager.yml
> chore: release v0.11.0
